site_name: EarthStat
site_description: Geospatial tool for statistical data extraction, resampling, and reprojecting, with intuitive integration and export features.
site_author: AbdelrahmanAmr3
site_url: https://AbdelrahmanAmr3.github.io/earthstat
repo_url: https://github.com/AbdelrahmanAmr3/earthstat

copyright: "Copyright &copy; 2024 - 2024 Abdelrahman Saleh"

theme:
    palette:
        - scheme: default
            # primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    logo: assests/logo_white.png
    # favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    # - git-revision-date-localized:
    #       enable_creation_date: true
    #       type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: false
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["*ignore.ipynb"]
          
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/AbdelrahmanAmr3/earthstat/issues
    - Examples:
        - examples/intro.ipynb
    - API Reference:
          - earthstat module: earthstat.md
          - Geospatial Metadata Extraction: geo_meta_extractor.md
          - Geospatial Data Converter: data_converter.md
          - Check and Fix Data Compatibility Issues: data_compatibility.md
          - Geospatial Data Preprocessing: geo_data_processing.md
          - Extract Statistical Information: analysis_aggregation.md
          - Utilities: utils.md
